CREATE INDEX IF NOT EXISTS "areas_slug_idx" ON "areas" USING btree ("slug");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ascents_created_by_idx" ON "ascents" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ascents_route_fk_idx" ON "ascents" USING btree ("route_fk");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "blocks_slug_idx" ON "blocks" USING btree ("slug");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "files_area_fk_idx" ON "files" USING btree ("area_fk");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "files_ascent_fk_idx" ON "files" USING btree ("ascent_fk");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "files_block_fk_idx" ON "files" USING btree ("block_fk");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "files_route_fk_idx" ON "files" USING btree ("route_fk");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "files_type_idx" ON "files" USING btree ("type");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "first_ascents_route_fk_idx" ON "first_ascents" USING btree ("route_fk");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "geolocations_area_fk_idx" ON "geolocations" USING btree ("area_fk");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "geolocations_block_fk_idx" ON "geolocations" USING btree ("block_fk");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "route_external_resources_route_fk_idx" ON "route_external_resources" USING btree ("route_fk");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "routes_slug_idx" ON "routes" USING btree ("slug");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "routes_block_fk_idx" ON "routes" USING btree ("block_fk");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "topo_routes_route_fk_idx" ON "topo_routes" USING btree ("route_fk");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "topo_routes_topo_fk_idx" ON "topo_routes" USING btree ("topo_fk");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "topos_block_fk_idx" ON "topos" USING btree ("block_fk");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_settings_auth_user_fk_idx" ON "user_settings" USING btree ("auth_user_fk");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_settings_user_fk_idx" ON "user_settings" USING btree ("user_fk");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "users_auth_user_fk_idx" ON "users" USING btree ("auth_user_fk");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "users_username_idx" ON "users" USING btree ("username");